-- Script para inserir setores de Aparecida de Goiânia
-- Primeiro, vamos verificar se já existem setores para Aparecida

-- 1. Verificar cidade de Aparecida de Goiânia
SELECT id, name FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO';

-- 2. Verificar setores existentes para Aparecida de Goiânia
SELECT s.id, s.name, c.name as cidade 
FROM sectors s 
JOIN cities c ON s.city_id = c.id 
WHERE c.name = 'Aparecida de Goiânia' AND c.state = 'GO';

-- 3. Deletar setores existentes de Aparecida de Goiânia (se necessário)
-- DESCOMENTE A LINHA ABAIXO SE QUISER DELETAR OS SETORES EXISTENTES
-- DELETE FROM sectors WHERE city_id IN (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO');

-- 4. Inserir todos os setores de Aparecida de Goiânia
-- (Substitua o ID da cidade pelo ID real retornado na consulta acima)

INSERT INTO sectors (name, city_id) VALUES
-- Jardins e Residenciais
('Jardim Alto Paraíso', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim São Conrado', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim das Cascatas', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Madre Germana', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Dom Bosco', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Quinta Da Boa Vista', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim dos Ipês', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Izaura', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Maranata', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Delfiori', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Rio Dourado', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Romana', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Cidade Satélite São Luiz', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Transbrasiliano', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Alzira', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Conjunto Residencial Storil', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Amazônia', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Brasília', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Conjunto Liberdade', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Primavera', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Brasília Sul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Conjunto Progresso', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Real', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Maria', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Cruzeiro do Sul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Santa Cecília', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Real', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Granjas Reunidas Nossa Sra. de Lourdes', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Recanto dos Emboabas', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Santo Antônio', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Bela Morada', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Residencial Alvaluz', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Santos Dumont', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Bonança', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Residencial Cândido de Queiroz', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila São Joaquim', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim das Esmeraldas', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Residencial Recanto do Cerrado', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila São Tomaz', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Imperial', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Residencial Santa Vitória', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Villasul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Luz', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor dos Afonsos', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Maria Inês', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Pampulha', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Mont Serrat', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Ocidente da Vila Brasília', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Nova Era', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Palácios', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Paraíso', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Bairro Cardoso', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Alvorada Oeste', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Bairro Ilda', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Alvorada Sul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Cidade Vera Cruz', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Chácaras Cond. Sonho Verde', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Cidade Empresarial', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Miramar', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Garavelo Residencial Park', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Nova Olinda', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Helvécia', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Itália', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardins Mônaco', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardins Viena', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardins Sevilha', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Real Grandeza', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Garavelo', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Recanto do Bosque', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Mariana', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Residencial Miramar', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Rosa', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Retiro do Bosque', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Rosa dos Ventos', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Planície', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Bairro Nova Cidade', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Residencial Anhambi', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Goiânia Park Sul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Residencial Araguaia', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Boa Esperança', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Residencial Caraíbas', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Buriti Sereno', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Residencial Goiani', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Canadá', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Residencial Norte-Sul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim das Hortências', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Residencial Pôr do Sol', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Florença', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Residencial Serra das Brisas', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Himalaia', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Riviera Sul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Tiradentes', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Aeroporto Sul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Tropical', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Belo Horizonte', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Veneza', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Colonial Sul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque das Nações', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor dos Bandeirantes', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Ibirapuera', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Residencial Campos Elísios', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parqville Pinheiros', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Bairro Independência', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Residencial Andrade Reis', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Cidade Livre', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Comendador Walmor', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Colina Azul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor dos Estados', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Independência Mansões', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Marista Sul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Monte Cristo', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Rio Vermelho', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Riviera', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Virgínia Parque', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Águas Claras', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Iracema', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Bairro Vera Cruz', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Rio Grande', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Centro de Aparecida', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Rosa do Sul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Chácaras Córrego das Lages', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Atalaia', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Res. Solar Garden 2', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Chácaras Santa Luzia', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Industrial Araguaia', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Res. Village Garavelo', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Fazenda Santo Antônio', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Itatiaia', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Araguaia', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Industrial Santo Antônio', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Karajá', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Oeste', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Ametista', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Rio das Pedras', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Aurea', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Polo Empresarial Goiás', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Santo André', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Belo Horizonte', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Res. Agenor Modesto', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Serra Dourada', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Copacabana', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Res. Brasicon 1', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Solar das Candeias', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Cristal', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Res. Maria Luiza', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Terra Prometida', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim dos Girassóis', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parqville Jacarandá', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Veiga Jardim Acréscimo', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Esplanada', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Res. Solar Central Park', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila São Manoel', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Ipanema', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Res. Solar Garden 1', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Ipiranga', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('All Park Polo Empresarial', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Cecília', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Franco', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Célia Maria', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Colorado', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Chácaras Marivânia', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim das Acácias', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Terra do Sol', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Chácaras São Pedro', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Eldorado', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vale do Sol', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Conjunto Habitacional Mabel', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Palmares', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Verde Vale', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Distrito Agroindustrial de Aparecida', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Repouso', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Adélia', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Expansul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Loteamento Santo Antônio', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Vila Irmãos Souza', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Expansul II', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Ind. Vice-Presid. José Alencar', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Fazenda Sto. Antônio (abaixo do Jd. Repouso)', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Ana Rosa', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Internacional Park', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Buenos Aires', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Casa Grande', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Continental', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('American Park', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Chácaras Bela Vista', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Bairro Itapuã', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Bela Vista', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Colinas de Homero', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim dos Buritis', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Cristalino', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim dos Pomares', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Mansões Paraíso', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Jardim Olímpico', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Morada dos Pássaros', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Flamboyant', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Papillon Park', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Trindade', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Floresta', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Trindade 2', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Hayala', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Trindade 3', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Parque Veiga Jardim', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Setor Tocantins', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Pontal Sul', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Sítios Santa Luzia', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Porto das Pedras', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Sítios Santa Luzia - Residencial', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO')),
('Seto', (SELECT id FROM cities WHERE name = 'Aparecida de Goiânia' AND state = 'GO'));

-- 5. Verificar quantos setores foram inseridos
SELECT COUNT(*) as total_setores_aparecida 
FROM sectors s 
JOIN cities c ON s.city_id = c.id 
WHERE c.name = 'Aparecida de Goiânia' AND c.state = 'GO';

-- 6. Listar todos os setores inseridos
SELECT s.name as setor, c.name as cidade 
FROM sectors s 
JOIN cities c ON s.city_id = c.id 
WHERE c.name = 'Aparecida de Goiânia' AND c.state = 'GO'
ORDER BY s.name;
